### ISSUE TITLE
Inserts `^]` character instead of whitespace when used with multicursors.nvim

### ISSUE THREAD

**Issue by Andrew15-5** [altermo/ultimate-autopair.nvim#63] opened 2023-11-25 20:00 UTC
Here is an archive: [ultimate-autopair.zip](https://github.com/altermo/ultimate-autopair.nvim/files/13465090/ultimate-autopair.zip)

You can test the bug (with `docker`, `docker compose`, `just`):
1. `unzip ultimate-autopair.zip`
2. `cd ultimate-autopair`
3. `just`
4. Press `ia `
5. See error

If instead `just wo` is run (step 3), then the ultimate-autopair.nvim plugin won't be executed, and a normal whitespace will be inserted in step 4.

`just`:
![image](https://github.com/altermo/ultimate-autopair.nvim/assets/37143421/e3a248fa-26d8-48ae-b61b-b129175e75ef)

`just wo`:
![image](https://github.com/altermo/ultimate-autopair.nvim/assets/37143421/c1a6749f-86f3-424d-aa95-83feb79a96e3)

P.S. [multicursors.nvim](https://github.com/smoka7/multicursors.nvim).

**Comment by altermo** [comment] 2023-11-25 21:13
This is a problem of multicursors.nvim not supporting the ctrl-] key. The ctrl-] key expands an abbreviation if detected, otherwise does nothing.
(`:help i_ctrl-]`) The reason why ultimate-autopair uses ctrl-], is cause it uses expr-mappings, which require an explicit ctrl-] to expand abbreviations.
If you don't use the space feature then disable it: add this to config: `space={enable=false}`

**Comment by Andrew15-5** [comment] 2023-11-25 21:21
> This is a problem of multicursors.nvim not supporting the ctrl-] key.

Is `i_CTRL-]` supposed to be supported by any plugin by default? If not, then you are saying that every other plugin must also (explicitly) support `i_CTRL-]` and I reckon a lot of authors/maintainers won't agree with you. Although I really don't know how either of two pluings are made, but if my guess is correct, then it really isn't the problem of multicursors.nvim, but rather of plugins, that (somehow/in some way) use the `i_CTRL-]`, i.e., ultimate-autopair.nvim.

**Comment by altermo** [comment] 2023-11-25 22:14
The problem is, I can't really do anything about it. Either ultimate-autopair.nvim has abbreviation support and breaks plugins that don't support `i_CTRL-]` (and tries to emulate insert-mode). Or it doesn't have abbreviation support and doesn't break those plugins.

Also, it is probably a Vim bug that `CTRL-]` activates `InsertCharPre` as other similar keys (like `i_ctrl-y`) don't activate `InsertCharPre`.
(multicursors.nvim (and other similar plugins) use `InsertCharPre` to get the typed character)

**Comment by zeertzjq** [comment] 2024-01-14 00:37
It seems that https://github.com/smoka7/multicursors.nvim may actually want to support abbreviations if possible, so making `i_CTRL-]` not trigger `InsertCharPre` actually makes it harder to support that.

**Comment by altermo** [comment] 2024-05-16 19:42
With the release of neovim 0.10, the thing that broke this has been fixed inside neovim. (see https://github.com/neovim/neovim/commit/da541c0af1ef6589548140ebce133ad3fecf6d42)

As I don't see any way of fixing this issue in the plugin itself (without some FFI nonsense) (to make it not break in neovim 0.9), I'll be closing this issue.

**Closed as completed by altermo** 2024-05-16 19:42 UTC

**Comment by Andrew15-5** [comment] 2024-05-16 20:57
I tested the reproduction example in v0.10.0 and it _werks_! Thank you! Now I can finally use this plugin again!) (I already forgot how awesome it was.)
